image: atlassian/default-image:2
image: cypress/browsers:latest
options:
  docker: true
  size: 2x
pipelines:
  custom:
    cypress:
      - variables:
          - name: browser_name
            default: "chrome"
            allowed-values:
              - "chrome"
              - "firefox"
              - "electron"
      - step:
          name: "E2E (Cypress) test"
          caches:
            - node
            - nextcache
            - npm
            - cypress
          script:
            - npm ci
            - npm run build
            - npm run start &
            - npm run cy:ci --browser $browser_name
          artifacts: # defining the artifacts to be passed to each future step.
            - cypress/reports/**
  default:
      - step:
          name: Build and Test
          image: node:19.8.1
          variables:
            NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: $NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            CLERK_SECRET_KEY: $CLERK_SECRET_KEY
            WEB_APP_URI: $CYPRESS_BASE_URL
          caches:
            - node
          script:
            - npm ci
            - npm run test:ci
            - npm run build
  branches:
      main:
        - step:
            name: SonarQube Analysis
            image: node:19.8.1
            script:
              - pipe: sonarsource/sonarcloud-scan:2.0.0
              - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
      feature/sk-489-testing-pipelines:
        - step:
            name: "Run Cypress Tests"
            image: cypress/included:latest
            caches:
              - node
              - cypress
            script:
              - echo $TEST_APP_ENV | base64 --decode --ignore-garbage > .env
              - cat .env
              - npm ci
              - npm run build
              - cat .env
              - npm run start &
              - npx wait-on http://localhost:3000
              # Clone Cypress repo in a separate directory
              - mkdir cypress-tests && cd cypress-tests
              - git clone git@bitbucket.org:segue-team/cypress.git --branch pipeline_test
              - cd cypress
              - npm ci
              # Run Cypress tests in headless mode
              # - npm run cy:alltests --browser chrome
              - npm run cy:permissions --browser chrome
              - apt-get update && apt-get install -y zip
              - cd cypress
              - ls -al
              - zip -r reports.zip reports
              - ls -al
              - pwd
            artifacts:
              - reports.zip
              - cypress-tests/cypress/**
            after-script:
              - ALERT_TYPE="success"
              - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then ALERT_TYPE="error" ; fi
              - pipe: atlassian/email-notify:0.3.11
                variables:
                  USERNAME: $SMTP_USERNAME
                  PASSWORD: $SMTP_PASSWORD
                  FROM: 'asara97911@gmail.com'
                  TO: 'asara97911@gmail.com'
                  HOST: 'smtp.gmail.com'
                  SUBJECT: '${ALERT_TYPE}:Bitbucket Pipe Notification for ${BITBUCKET_BRANCH}'
                  ATTACHMENTS: 'reports.zip'
            artifacts:
              - cypress-tests/cypress/reports/**
              - cypress-tests/cypress/**
        # - step:
        #     name: "Generate Test Report"
        #     script:
        #       - ls -al
        #       - npm install -g mochawesome-merge mochawesome-report-generator
        #       - mochawesome-merge reports/mocha/*.json > reports/mochawesome.json
        #       - marge reports/mochawesome.json -f report -o reports
        #     artifacts:
        #       - cypress-tests/cypress/reports/**
        # - step:
        #     name: "Send Email with Test Report"
        #     script:
        #       - pipe: atlassian/email-notify:0.7.0
        #         variables:
        #           USERNAME: $SMTP_USERNAME
        #           PASSWORD: $SMTP_PASSWORD
        #           FROM: 'asara97911@gmail.com'
        #           TO: 'asara97911@gmail.com'
        #           HOST: 'smtp.gmail.com'
        #           SUBJECT: 'Cypress Test Report'
        #           BODY_HTML: '<h1>Cypress Test Report</h1><p>Please find the test report attached.</p>'
        #           ATTACHMENTS: 'cypress-tests/cypress/reports/report.html'
definitions:
  caches:
    npm: ~/.npm
    cypress: ~/.cache
    nextcache: ~/.next/cache
  services:
    docker:
      memory: 4096