image: atlassian/default-image:2
image: cypress/browsers:latest
options:
  docker: true
  size: 2x
pipelines:
  branches:
    main:
      - step:
          name: SonarQube Analysis
          image: node:19.8.1
          script:
            - pipe: sonarsource/sonarcloud-scan:2.0.0
            - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
  custom:
    cypress:
      - variables:
          - name: browser_name
            default: "chrome"
            allowed-values:
              - "chrome"
              - "firefox"
              - "electron"
      - step:
          name: "E2E (Cypress) test"
          caches:
            - node
            - nextcache
            - npm
            - cypress
          script:
            - npm ci
            - npm run build
            - npm run start &
            - npm run cy:ci --browser $browser_name
          artifacts: # defining the artifacts to be passed to each future step.
            - cypress/reports/**
  default:
    - parallel:
        - step:
            name: Build
            image: node:19.8.1
            variables:
              NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: $NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
              CLERK_SECRET_KEY: $CLERK_SECRET_KEY
              WEB_APP_URI: $CYPRESS_BASE_URL
            caches:
              - node
            services:
              - docker
            script:
              - npm install
              - npm run test:ci
              - npm run build
definitions:
  caches:
    npm: ~/.npm
    cypress: ~/.cache
    nextcache: ~/.next/cache
  services:
    docker:
      memory: 4096