image: atlassian/default-image:2


options:
  docker: true
  size: 4x
pipelines:

  custom:
    cypress:
#      - step:
#          name: "Build and Push Docker Image"
#          script:
#            - docker info
#            - docker build -t jan961/cypress-segue:myimage .
#            - docker login -u jan961 -p aQtZ9icpLhpR4hG
#            - docker  push jan961/cypress-segue:myimage

      - step:
          size: 4x
          name: "Run Cypress Tests"
          image: jan961/cypress-segue:myimage # get the docker image from DockerHub
          caches:
            - node
            - cypress
            - nextcache
          timeout:
          script:
            - echo "Current directory is $(pwd)"
            - ls
            # Downgrade npm
            - npm install -g npm@9.6.7
             # Get the start-server-and-test utility that will keep the server running while tests are run
            - npm install -g start-server-and-test
            - apt-get update && apt-get install -y zip
            - mkdir segue-dir
            # enable pattern matching in bash
            - shopt -s extglob
            # include hidden files such as .git (which here is apparently needed for husky)
            - shopt -s dotglob
            # Copy the contents of the current directory (all of Segue) to the segue-dir directory
            - mv !(segue-dir) segue-dir/
            - echo "The contents of the current working directory are $(ls)"
            - echo " The contents of the segue-dir are $(ls segue-dir)"
            - cd segue-dir &&  npm install
            - echo $TEST_APP_ENV | base64 --decode --ignore-garbage > .env
            - cat .env
            - npm run build
            - cd ..
            # Clone the Cypress repository into a dir at the same level as Segue
            - git clone git@bitbucket.org:segue-team/cypress.git && cd cypress
            - git checkout staging
            - npm install
            - npx cypress install
            - cd ..
            - DEBUG=start-server-and-test start-server-and-test "npm --prefix segue-dir/ run start" http://localhost:3000 "npm --prefix cypress/ run cy:alltests"
#            - npm --prefix segue-dir/ run start &
#            - npx wait-on http://localhost:3000 &
#            - npm --prefix cypress/ run cy:alltests
            - cd cypress
            - echo "Merging reports"
            # Merge reports from different spec files
            - npx mochawesome-merge cypress/results/*.json -o output.json
            - if [ -e output.json ]; then echo "filename output.json exists"; else echo "output.json does not exist"; fi
            # Generate HTML report from merged JSON
            - npx marge output.json
            - if [ -e mochawesome-report/output.html ]; then echo "mochawesome-report/output.html exists"; else echo "mochawesome-report/output.html does not exist"; fi
            # Generate email report template HTML file that will form the body of the email
            - node create-email-report
            - if [ -e email-report.html ]; then echo "email-report.html exists"; else echo "email-report.html does not exist"; fi
            # Zip the full report directory
            - zip -r full-report.zip mochawesome-report/
            - if [ -e full-report.zip ]; then echo " full-report.zip exists"; else echo "full-report.zip does not exist"; fi
          after-script:

            # Set alert type based on test results
            - ALERT_TYPE="success"
            - |
              if [[ $(jq '.stats.failures' output.json) -ne 0 ]]; then 
                ALERT_TYPE="error"
                echo "Tests failed but continuing with report generation"
              fi
            - ALERT_TYPE="success"
            - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then
              ALERT_TYPE="error";
              echo "Tests failed but continuing with report generation";
              fi
            # Use pre-built Atlassian email-notify pipe with the variables as below to send email with test results
            - pipe: atlassian/email-notify:0.13.2
              variables:
                USERNAME: $SMTP_USERNAME
                PASSWORD: $SMTP_PASSWORD
                FROM: $SMTP_USERNAME
                TO: jan@segue360.co.uk
                HOST: 'smtp.gmail.com'
                SUBJECT: '${ALERT_TYPE}: Segue Integration Tests for ${BITBUCKET_BRANCH}'
                BODY_HTML: 'cypress/email-report.html'
                ATTACHMENTS: 'cypress/full-report.zip'
          artifacts:
            - cypress/mochawesome-report
            - cypress/full-report.zip
            - cypress/email-report.html
            - cypress/cypress/results/**
            - cypress/cypress/screenshots/**


  default:
    - step:
        name: Build and Test
        image: node:18.20.4
        variables:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: $NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          CLERK_SECRET_KEY: $CLERK_SECRET_KEY
          WEB_APP_URI: $CYPRESS_BASE_URL
        caches:
          - node
        script:
          - npm install
          - npm run test:ci
          - npm run build
    - step:
        name: SonarQube Analysis
        image: node:18.20.4
        script:
          - pipe: sonarsource/sonarcloud-scan:2.0.0
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
definitions:
  caches:
    npm: ~/.npm
    cypress: ~/.cache
    nextcache: ~/.next/cache
  services:
    docker:
      memory: 4096






