image: atlassian/default-image:2


options:
  docker: true
  size: 4x
pipelines:

  custom:
    cypress:
#      - step:
#          name: "Build and Push Docker Image"
#          script:
#            - docker info
#            - docker build -t jan961/cypress-segue:myimage .
#            - docker login -u jan961 -p aQtZ9icpLhpR4hG
#            - docker  push jan961/cypress-segue:myimage

      - step:
          size: 4x
          name: "Run Cypress Tests"
          image: jan961/cypress-segue:myimage
          caches:
            - node
            - cypress
            - nextcache
          timeout:
          script:
            - npm install -g npm@9.6.7
            - echo "NPM version is $(npm -v)"
            -  apt-get install -y zip
            - npm install
            - npm install start-server-and-test
            - echo $TEST_APP_ENV | base64 --decode --ignore-garbage > .env
            - cat .env
            - npm run build
            - mkdir cypress-tests && cd cypress-tests
            - git clone git@bitbucket.org:segue-team/cypress.git && cd cypress
            - git checkout staging
            - npm install
            - npx cypress install
            - cd ../..
            - npx start-server-and-test "npm run start" http://localhost:3000 "npm --prefix cypress-tests/cypress run cy:alltests"
            # - npm run cy:permissions --browser chrome
            - cd cypress-tests/cypress
            - npx mochawesome-merge cypress/results/*.json -o output.json
            - npx marge output.json
            - node create-email-report
            - zip -r full-report.zip mochawsome-report/
          after-script:

            # Set alert type based on test results
            - ALERT_TYPE="success"
            - |
              if [[ $(jq '.stats.failures' output.json) -ne 0 ]]; then 
                ALERT_TYPE="error"
                echo "Tests failed but continuing with report generation"
              fi
            - ALERT_TYPE="success"
            - if [[ $BITBUCKET_EXIT_CODE -ne 0 ]]; then
              ALERT_TYPE="error";
              echo "Tests failed but continuing with report generation";
              fi
            - pipe: atlassian/email-notify:0.13.2
              variables:
                USERNAME: $SMTP_USERNAME
                PASSWORD: $SMTP_PASSWORD
                FROM: $SMTP_USERNAME
                TO: jan@segue360.co.uk
                HOST: 'smtp.gmail.com'
                SUBJECT: '${ALERT_TYPE}: Segue Integration Tests for ${BITBUCKET_BRANCH}'
                BODY_HTML: 'cypress-tests/cypress/email-report.html'
                ATTACHMENTS: 'cypress-tests/cypress/full-report.zip'
          artifacts:
            - cypress-tests/cypress/cypress/results/**
            - cypress-tests/cypress/mochawesome-report
            - cypress-tests/cypress/full-report.zip
            - cypress-tests/cypress/email-report.html


  default:
    - step:
        name: Build and Test
        image: node:18.20.4
        variables:
          NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: $NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          CLERK_SECRET_KEY: $CLERK_SECRET_KEY
          WEB_APP_URI: $CYPRESS_BASE_URL
        caches:
          - node
        script:
          - npm install
          - npm run test:ci
          - npm run build
    - step:
        name: SonarQube Analysis
        image: node:18.20.4
        script:
          - pipe: sonarsource/sonarcloud-scan:2.0.0
          - pipe: sonarsource/sonarcloud-quality-gate:0.1.6
definitions:
  caches:
    npm: ~/.npm
    cypress: ~/.cache
    nextcache: ~/.next/cache
  services:
    docker:
      memory: 4096






